spring:
  application:
    name: RideSync Solutions
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:ridesyncdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console (for development/demo)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# SpringDoc OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

# Application Info
info:
  app:
    name: RideSync Solutions
    description: Hackathon-winning ride-sharing platform
    version: 1.0.0
    java-version: ${java.version}
    spring-boot-version: ${spring-boot.version}

# Logging Configuration
logging:
  level:
    com.ridesync: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
